<?xml version="1.0"?>
<package format="2">
  <name>cloudini_ros</name>
  <version>0.10.1</version>
  <description>
  Main library of Cloudini, the pointcloud compression library (ROS1 port)
  </description>

  <maintainer email="davide.faconti@gmail.com">Davide Faconti</maintainer>

  <license>Apache</license>

  <author>Davide Faconti</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cloudini_lib</depend>
  <depend>roscpp</depend>
  <depend>sensor_msgs</depend>
  <depend>rosbag</depend>
  <depend>rosbag_storage</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>topic_tools</depend>

</package>
