<?xml version="1.0"?>
<package format="2">
  <name>cloudini_lib</name>
  <version>0.10.1</version>
  <description>
  Main library of Cloudini, the pointcloud compression library (ROS1 port)
  </description>

  <maintainer email="davide.faconti@gmail.com">Davide Faconti</maintainer>

  <license>Apache 2.0</license>

  <author>Davide Faconti</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>pcl_ros</depend>

  <test_depend>gtest</test_depend>

</package>
